Repository NeuralNetworkVerification/Marabou, pull requests merged in 2020-04, with the labels that each got.

#191 Optimize floatutils
  src/common/FloatUtils.cpp
  src/common/FloatUtils.h
Labels: performance, simple

#237 use sat/unsat instead of SAT/UNSAT
  README.md
  maraboupy/Marabou.py
  maraboupy/MarabouNetwork.py
  maraboupy/examples/Example Notebook.ipynb
  maraboupy/examples/MarabouCoreExample.py
  regress/regress0/CMakeLists.txt
  regress/regress1/CMakeLists.txt
  regress/regress2/CMakeLists.txt
  regress/run_regression.py
  src/engine/DnCManager.cpp
  src/engine/DnCWorker.cpp
  src/engine/Engine.cpp
  src/engine/Marabou.cpp
  src/input_parsers/mps_example/main.cpp
Labels: major, refactor, simple

#246 Optimize iszero
  src/common/FloatUtils.h
Labels: performance, simple

#250 Comments
  src/engine/AbsoluteValueConstraint.h
  src/engine/MaxConstraint.h
  src/engine/ReluConstraint.h
Labels: minor

#249 Symbolic bound tightening in NLR
  maraboupy/MarabouCore.cpp
  maraboupy/MarabouNetworkNNet.py
  src/configuration/GlobalConfiguration.cpp
  src/configuration/GlobalConfiguration.h
  src/engine/CMakeLists.txt
  src/engine/Engine.cpp
  src/engine/Engine.h
  src/engine/InputQuery.cpp
  src/engine/InputQuery.h
  src/engine/NetworkLevelReasoner.cpp
  src/engine/NetworkLevelReasoner.h
  src/engine/Preprocessor.cpp
  src/engine/SymbolicBoundTightener.cpp
  src/engine/SymbolicBoundTightener.h
  src/engine/tests/Test_NetworkLevelReasoner.h
  src/engine/tests/Test_SymbolicBoundTightener.h
  src/input_parsers/AcasParser.cpp
  src/query_loader/tests/Test_QueryLoader.h
Labels: enhancement, performance

#251 Symbolic bound tightening over absolute values
  src/engine/AbsoluteValueConstraint.cpp
  src/engine/Equation.cpp
  src/engine/NetworkLevelReasoner.cpp
  src/engine/NetworkLevelReasoner.h
  src/engine/tests/Test_NetworkLevelReasoner.h
  src/system_tests/Test_AbsoluteValue.h
Labels: enhancement, feature

#255 Better interval propagation
  src/engine/NetworkLevelReasoner.cpp
Labels: minor
