Repository NeuralNetworkVerification/Marabou, pull requests merged in 2020-03, with the labels that each got.

#224 perform sbt on both branches
  src/engine/Engine.cpp
Labels: minor, performance

#221 Add support for different branching heuristics
  src/configuration/GlobalConfiguration.cpp
  src/configuration/GlobalConfiguration.h
  src/engine/DivideStrategy.h
  src/engine/Engine.cpp
  src/engine/Engine.h
  src/engine/IEngine.h
  src/engine/PiecewiseLinearConstraint.cpp
  src/engine/PiecewiseLinearConstraint.h
  src/engine/ReluConstraint.cpp
  src/engine/SmtCore.cpp
  src/engine/SmtCore.h
  src/engine/tests/MockEngine.h
  src/input_parsers/AcasParser.cpp
Labels: feature, moderate

#232 Improved Relu splits
  CMakeLists.txt
  src/engine/ReluConstraint.cpp
  src/engine/tests/Test_ReluConstraint.h
Labels: minor, performance

#235 Static flag in cmake
  CMakeLists.txt
  README.md
Labels: feature, minor
