Repository NeuralNetworkVerification/Marabou, pull requests merged in 2020-06, with the labels that each got.

#266 Polarity-based Splitting Heuristics
  src/configuration/GlobalConfiguration.cpp
  src/configuration/GlobalConfiguration.h
  src/engine/DivideStrategy.h
  src/engine/Engine.cpp
  src/engine/InputQuery.cpp
  src/engine/MarabouError.h
  src/engine/NetworkLevelReasoner.cpp
  src/engine/NetworkLevelReasoner.h
  src/engine/ReluConstraint.cpp
  src/engine/ReluConstraint.h
  src/engine/SmtCore.cpp
  src/engine/SmtCore.h
  src/input_parsers/AcasParser.cpp
Labels: feature

#271 NLR for networks with a general, feed-forward topology
  CMakeLists.txt
  maraboupy/MarabouCore.cpp
  maraboupy/test/test_onnx.py
  src/CMakeLists.txt
  src/engine/CMakeLists.txt
  src/engine/DivideStrategy.h
  src/engine/DnCManager.cpp
  src/engine/Engine.cpp
  src/engine/Engine.h
  src/engine/Equation.cpp
  src/engine/Equation.h
  src/engine/InputQuery.cpp
  src/engine/InputQuery.h
  src/engine/LargestIntervalDivider.cpp
  src/engine/MarabouError.h
  src/engine/NetworkLevelReasoner.cpp
  src/engine/NetworkLevelReasoner.h
  src/engine/Preprocessor.cpp
  src/engine/Preprocessor.h
  src/engine/ReluConstraint.cpp
  src/engine/ReluConstraint.h
  src/engine/SmtCore.cpp
  src/engine/SmtCore.h
  src/engine/tests/Test_DnCWorker.h
  src/engine/tests/Test_Preprocessor.h
  src/input_parsers/AcasParser.cpp
  src/input_parsers/InputParserError.h
  src/input_parsers/PropertyParser.cpp
  src/nlr/CMakeLists.txt
  src/nlr/Layer.cpp
  src/nlr/Layer.h
  src/nlr/NetworkLevelReasoner.cpp
  src/nlr/NetworkLevelReasoner.h
  src/nlr/NeuronIndex.h
  src/nlr/tests/Test_NetworkLevelReasoner.h
Labels: enhancement, major, refactor

#301 Openblas nlr
  CMakeLists.txt
  COPYING
  src/common/CMakeLists.txt
  src/common/MatrixMultiplication.cpp
  src/common/MatrixMultiplication.h
  src/common/tests/Test_MatrixMultiplication.h
  src/engine/Engine.cpp
  src/nlr/Layer.cpp
  src/nlr/Layer.h
  tools/get-openBLAS.sh
Labels: performance

#302 Cutoffs for LP and MILP queries
  src/common/GurobiWrapper.cpp
  src/common/GurobiWrapper.h
  src/configuration/GlobalConfiguration.cpp
  src/configuration/GlobalConfiguration.h
  src/nlr/LPFormulator.cpp
  src/nlr/MILPFormulator.cpp
  src/nlr/MILPFormulator.h
Labels: feature, minor, performance
