Repository NeuralNetworkVerification/Marabou, pull requests merged in 2024-02, with the labels that each got.

#712 get rid of torch as requirement
  CHANGELOG.md
  CMakeLists.txt
  README.md
  maraboupy/MarabouNetworkONNX.py
  maraboupy/test_requirements.txt
  pyproject.toml
  tools/download_onnx.sh
Labels: minor

#720 Fix bug in notifyLower/UpperBounds in the Sigmoid class
  regress/regress1/input_queries/evaluate_tanh_network_sat.ipq
  src/engine/SigmoidConstraint.cpp
Labels: minor

#725 Print errors on stderr rather than stdout
  CHANGELOG.md
  maraboupy/MarabouCore.cpp
  src/engine/MarabouMain.cpp
Labels: bug, minor

#733 Fixed bugs with Sigmoid layers in C++ ONNX parser
  CHANGELOG.md
  src/input_parsers/NetworkParser.cpp
Labels: bug

#732 Implement the Cast operator in C++ ONNX parser
  CHANGELOG.md
  resources/onnx/layer-zoo/add.onnx
  resources/onnx/layer-zoo/batchnorm.onnx
  resources/onnx/layer-zoo/cast_int_to_float.onnx
  resources/onnx/layer-zoo/constant.onnx
  resources/onnx/layer-zoo/conv.onnx
  resources/onnx/layer-zoo/flatten.onnx
  resources/onnx/layer-zoo/gemm.onnx
  resources/onnx/layer-zoo/identity.onnx
  resources/onnx/layer-zoo/matmul.onnx
  resources/onnx/layer-zoo/maxpool.onnx
  resources/onnx/layer-zoo/onnx-layer-zoo.py
  resources/onnx/layer-zoo/relu.onnx
  resources/onnx/layer-zoo/reshape.onnx
  resources/onnx/layer-zoo/reshape_with_dimension_inference.onnx
  resources/onnx/layer-zoo/sigmoid.onnx
  resources/onnx/layer-zoo/sub.onnx
  resources/onnx/layer-zoo/tanh.onnx
  resources/onnx/layer-zoo/transpose.onnx
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/tests/Test_OnnxParser.h
Labels: enhancement

#731 Support multiple outputs in C++ ONNX parser
  CHANGELOG.md
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
Labels: enhancement

#738 Implement the Squeeze operator in C++ ONNX parser
  CHANGELOG.md
  resources/onnx/layer-zoo/onnx-layer-zoo.py
  resources/onnx/layer-zoo/squeeze.onnx
  resources/onnx/layer-zoo/squeeze_with_axes.onnx
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
  src/input_parsers/TensorUtils.cpp
  src/input_parsers/TensorUtils.h
  src/input_parsers/tests/Test_OnnxParser.h
Labels: enhancement

#742 use alpha in leaky relu python parser
  maraboupy/MarabouNetworkONNX.py
Labels: bug, minor

#747 Moved generic constraints from OnnxParser to NetworkParser
  src/input_parsers/NetworkParser.cpp
  src/input_parsers/NetworkParser.h
  src/input_parsers/OnnxParser.cpp
Labels: refactor

#741 Implement LeakyRelu operation in C++ ONNX parser
  CHANGELOG.md
  maraboupy/MarabouNetwork.py
  resources/onnx/layer-zoo/leakyRelu.onnx
  resources/onnx/layer-zoo/onnx-layer-zoo.py
  src/input_parsers/NetworkParser.cpp
  src/input_parsers/NetworkParser.h
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
  src/input_parsers/tests/Test_OnnxParser.h
Labels: enhancement

#745 Split `ONNXParser` from `MarabouONNXNetwork` in preparation for replacing with C++ implementation
  CHANGELOG.md
  maraboupy/Marabou.py
  maraboupy/MarabouNetwork.py
  maraboupy/MarabouNetworkONNX.py
  maraboupy/docs/Develop/3_Tests.md
  maraboupy/parsers/InputQueryBuilder.py
  maraboupy/parsers/ONNXParser.py
  maraboupy/test/test_equation.py
  maraboupy/test/test_network.py
  maraboupy/test/test_nnet_extensions.py
  maraboupy/test/test_onnx.py
  maraboupy/test/test_query.py
  resources/runMarabou.py
Labels: refactor

#748 Implement Unsqueeze operation in C++ ONNX parser
  CHANGELOG.md
  resources/onnx/layer-zoo/onnx-layer-zoo.py
  resources/onnx/layer-zoo/unsqueeze.onnx
  src/common/Vector.h
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
  src/input_parsers/TensorUtils.cpp
  src/input_parsers/TensorUtils.h
  src/input_parsers/tests/Test_OnnxParser.h
Labels: enhancement

#753 Fixed ill-specified int type in ONNX parsing
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
  src/input_parsers/TensorUtils.h
Labels: bug

#752 Touch up README.md and run `clang-format` via precommit hooks
  .pre-commit-config.yaml
  README.md
  tools/clang-format-src.sh
Labels: refactor

#757 Refactor C++ ONNXParser to a pure style that takes in an InputQueryBuilder as an argument.
  src/engine/DnCMarabou.cpp
  src/engine/Marabou.cpp
  src/input_parsers/InputQueryBuilder.cpp
  src/input_parsers/InputQueryBuilder.h
  src/input_parsers/OnnxParser.cpp
  src/input_parsers/OnnxParser.h
  src/input_parsers/tests/Test_OnnxParser.h
  src/input_parsers/tests/Test_VnnLibParser.h
Labels: refactor

#759 Remove output variable reindexing in Python API
  CHANGELOG.md
  maraboupy/Marabou.py
  maraboupy/MarabouNetworkONNX.py
  maraboupy/MarabouNetworkTF.py
  maraboupy/parsers/ONNXParser.py
  maraboupy/test/test_onnx.py
Labels: refactor

#765 Reorganise main CMakeLists file
  CMakeLists.txt
Labels: refactor

#767 Refactor CMakeList and download scripts to use versions from a single source
  .gitignore
  CMakeLists.txt
  pyproject.toml
  tools/download_boost.sh
  tools/download_onnx.sh
  tools/download_openBLAS.sh
  tools/download_protobuf.sh
  tools/download_pybind11.sh
Labels: refactor

#768 Fix python API examples
  .github/workflows/ci.yml
  maraboupy/examples/0_NNetExample.py
  maraboupy/examples/1_TensorflowExample.py
  maraboupy/examples/2_ONNXExample.py
  maraboupy/examples/4_DncExample.py
  maraboupy/examples/5_DisjunctionConstraintExample.py
Labels: bug

#769 fix constant addend in python onnx parser
  maraboupy/parsers/ONNXParser.py
  maraboupy/test/test_onnx.py
  resources/onnx/yizhak_net.onnx
Labels: bug
